import type { Metadata } from "next";
import { Poppins, Satisfy } from "next/font/google";
import { Header } from "@/components/Header/Header"
import { twMerge } from "@/utils/twMerge"
import "./globals.css";

const Poppins_Sans_Serif = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
})

const satisfy = Satisfy({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-Satisfy",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="pt-BR"
      className={`${Poppins_Sans_Serif.variable} ${satisfy.variable}`}
    >
      <body
      className={twMerge(
        "bg-slate-950 text-slate-100 relative",
      )}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
