import type { Metadata } from "next";
import { Poppins, La_Belle_Aurore } from "next/font/google";
import "./globals.css";

const Poppins_Sans_Serif = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
})

const La_Belle_Aurore_Regular = La_Belle_Aurore({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-la-belle-aurore-regular",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="pt-BR"
      className={`${Poppins_Sans_Serif.variable} ${La_Belle_Aurore_Regular.variable}`}
    >
      <body>{children}</body>
    </html>
  );
}
